gradientMode: "hue"
cellIdPreamble: "45-7Ad6vYY371lEwY7TN-"
cells: 
  3:
    dataRef: "Disk One Status"
    fillColor:
      # See labelColor
      dataRef: "Disk One Status"
      # bespokeDataRef: null 
      # See labelColor
      datapoint: "last"
      # See labelColor
      gradientMode: "hue"
      # See labelColor
      thresholds:
        - {color: "semi-dark-green", level: 1}
        - {color: "orange", level: 2}
        - {color: "red", level: 3}
        - {color: "red", level: 4}
    linkRef: "grafana-home"
