gradientMode: "hue"
cells: 
  45-7Ad6vYY371lEwY7TN-3:
    dataRef: "Disk One Status"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
      fillColor:
        thresholds:
          - {color: "orange", level: 1}
          - {color: "green", level: 2}
          - {color: "red", level: 3}
          - {color: "red", level: 4}	
    linkRef: "grafana-home"
