gradientMode: "hue"
cells: 
  g7FJhC3SirEoIeaR-nqI-5:
    dataRef: "Disk One Status"
    fillColor:
      # See labelColor
      dataRef: "Disk One Status"
      bespokeDataRef: null 
      # See labelColor
      datapoint: "last"
      # See labelColor
      gradientMode: "hue"
      # See labelColor
      thresholds:
        - {color: "orange", level: 1}
        - {color: "semi-dark-green", level: 2}
        - {color: "red", level: 3}
        - {color: "red", level: 4}
    linkRef: "grafana-home"
