cells: 
  g7FJhC3SirEoIeaR-nqI-6:
    dataRef: "Disk One Status"
    fillColor:
      dataRef: "Disk One Status"
      datapoint: "last"
      thresholds:
        - {color: "orange", level: 1}
        - {color: "semi-dark-green", level: 2}
        - {color: "red", level: 3}
        - {color: "red", level: 4}
    linkRef: "grafana-home"
