gradientMode: "hue"
cellIdPreamble: "g7FJhC3SirEoIeaR-nqI-"
cells: 
  5:
    dataRef: "Disk One Status"
    fillColor:
      # See labelColor
      dataRef: "Disk One Status"
      bespokeDataRef: null 
      # See labelColor
      datapoint: "last"
      # See labelColor
      gradientMode: "hue"
      # See labelColor
      thresholds:
        - {color: "orange", level: 1}
        - {color: "semi-dark-green", level: 2}
        - {color: "red", level: 3}
        - {color: "red", level: 4}
    linkRef: "grafana-home"
  6:
    dataRef: "Disk Two Status"
    fillColor:
      # See labelColor
      dataRef: "Disk Two Status"
      bespokeDataRef: null 
      # See labelColor
      datapoint: "last"
      # See labelColor
      gradientMode: "hue"
      # See labelColor
      thresholds:
        - {color: "orange", level: 1}
        - {color: "semi-dark-green", level: 2}
        - {color: "red", level: 3}
        - {color: "red", level: 4}
    linkRef: "grafana-home"
  8:
    dataRef: "Disk Three Status"
    fillColor:
      # See labelColor
      dataRef: "Disk Three Status"
      bespokeDataRef: null 
      # See labelColor
      datapoint: "last"
      # See labelColor
      gradientMode: "hue"
      # See labelColor
      thresholds:
        - {color: "orange", level: 1}
        - {color: "semi-dark-green", level: 2}
        - {color: "red", level: 3}
        - {color: "red", level: 4}
    linkRef: "grafana-home"
  9:
    dataRef: "Disk Four Status"
    fillColor:
      # See labelColor
      dataRef: "Disk Four Status"
      bespokeDataRef: null 
      # See labelColor
      datapoint: "last"
      # See labelColor
      gradientMode: "hue"
      # See labelColor
      thresholds:
        - {color: "orange", level: 1}
        - {color: "semi-dark-green", level: 2}
        - {color: "red", level: 3}
        - {color: "red", level: 4}
    linkRef: "grafana-home"
  10:
    dataRef: "Disk Five Status"
    fillColor:
      # See labelColor
      dataRef: "Disk Five Status"
      bespokeDataRef: null 
      # See labelColor
      datapoint: "last"
      # See labelColor
      gradientMode: "hue"
      # See labelColor
      thresholds:
        - {color: "orange", level: 1}
        - {color: "semi-dark-green", level: 2}
        - {color: "red", level: 3}
        - {color: "red", level: 4}
    linkRef: "grafana-home"
  11:
    dataRef: "Disk Six Status"
    fillColor:
      # See labelColor
      dataRef: "Disk Six Status"
      bespokeDataRef: null 
      # See labelColor
      datapoint: "last"
      # See labelColor
      gradientMode: "hue"
      # See labelColor
      thresholds:
        - {color: "orange", level: 1}
        - {color: "semi-dark-green", level: 2}
        - {color: "red", level: 3}
        - {color: "red", level: 4}
    linkRef: "grafana-home"
  12:
    dataRef: "Disk Seven Status"
    fillColor:
      # See labelColor
      dataRef: "Disk Seven Status"
      bespokeDataRef: null 
      # See labelColor
      datapoint: "last"
      # See labelColor
      gradientMode: "hue"
      # See labelColor
      thresholds:
        - {color: "orange", level: 1}
        - {color: "semi-dark-green", level: 2}
        - {color: "red", level: 3}
        - {color: "red", level: 4}
    linkRef: "grafana-home"
  13:
    dataRef: "Disk Eight Status"
    fillColor:
      # See labelColor
      dataRef: "Disk Eight Status"
      bespokeDataRef: null 
      # See labelColor
      datapoint: "last"
      # See labelColor
      gradientMode: "hue"
      # See labelColor
      thresholds:
        - {color: "orange", level: 1}
        - {color: "semi-dark-green", level: 2}
        - {color: "red", level: 3}
        - {color: "red", level: 4}
    linkRef: "grafana-home"