cells: 
  My1_Hk7sBKh1Tc-6wi9T-39:
    dataRef: "Drive [8]: Status indicator"
    fillColor:
      dataRef: "Drive [8]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-38:
    dataRef: "Drive [9]: Status indicator"
    fillColor:
      dataRef: "Drive [9]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-37:
    dataRef: "Drive [10]: Status indicator"
    fillColor:
      dataRef: "Drive [10]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-36:
    dataRef: "Drive [11]: Status indicator"
    fillColor:
      dataRef: "Drive [11]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-35:
    dataRef: "Drive [12]: Status indicator"
    fillColor:
      dataRef: "Drive [12]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-34:
    dataRef: "Drive [13]: Status indicator"
    fillColor:
      dataRef: "Drive [13]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-33:
    dataRef: "Drive [14]: Status indicator"
    fillColor:
      dataRef: "Drive [14]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-32:
    dataRef: "Drive [15]: Status indicator"
    fillColor:
      dataRef: "Drive [15]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-31:
    dataRef: "Drive [16]: Status indicator"
    fillColor:
      dataRef: "Drive [16]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-30:
    dataRef: "Drive [17]: Status indicator"
    fillColor:
      dataRef: "Drive [17]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-29:
    dataRef: "Drive [18]: Status indicator"
    fillColor:
      dataRef: "Drive [18]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-28:
    dataRef: "Drive [19]: Status indicator"
    fillColor:
      dataRef: "Drive [19]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-27:
    dataRef: "Drive [20]: Status indicator"
    fillColor:
      dataRef: "Drive [20]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-26:
    dataRef: "Drive [21]: Status indicator"
    fillColor:
      dataRef: "Drive [21]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-6:
    dataRef: "Drive [22]: Status indicator"
    fillColor:
      dataRef: "Drive [22]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-5:
    dataRef: "Drive [23]: Status indicator"
    fillColor:
      dataRef: "Drive [23]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
