gradientMode: "hue"
cellIdPreamble: "g7FJhC3SirEoIeaR-nqI-"
cells: 
  5:
    dataRef: "Disk One Status"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "normalized"
    linkRef: "grafana-home"
  6:
    dataRef: "Disk Two Status"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "normalized"
    linkRef: "grafana-home"
