cells: 
  My1_Hk7sBKh1Tc-6wi9T-39:
    dataRef: "SV10TPEHV12: Drive [8]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [8]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-38:
    dataRef: "SV10TPEHV12: Drive [9]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [9]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-37:
    dataRef: "SV10TPEHV12: Drive [10]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [10]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-36:
    dataRef: "SV10TPEHV12: Drive [11]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [11]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-35:
    dataRef: "SV10TPEHV12: Drive [12]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [12]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-34:
    dataRef: "SV10TPEHV12: Drive [13]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [13]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-33:
    dataRef: "SV10TPEHV12: Drive [14]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [14]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-32:
    dataRef: "SV10TPEHV12: Drive [15]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [15]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-31:
    dataRef: "SV10TPEHV12: Drive [16]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [16]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-30:
    dataRef: "SV10TPEHV12: Drive [17]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [17]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-29:
    dataRef: "SV10TPEHV12: Drive [18]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [18]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-28:
    dataRef: "SV10TPEHV12: Drive [19]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [19]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-27:
    dataRef: "SV10TPEHV12: Drive [20]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [20]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-26:
    dataRef: "SV10TPEHV12: Drive [21]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [21]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-6:
    dataRef: "SV10TPEHV12: Drive [22]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [22]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-5:
    dataRef: "SV10TPEHV12: Drive [23]: Status indicator"
    fillColor:
      dataRef: "SV10TPEHV12: Drive [23]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-242:
    dataRef: "SV10TEPHV13: Drive [8]: Status indicator"
    fillColor:
      dataRef: "SV10TEPHV13: Drive [8]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-243:
    dataRef: "SV10TEPHV13: Drive [9]: Status indicator"
    fillColor:
      dataRef: "SV10TEPHV13: Drive [9]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-244:
    dataRef: "SV10TEPHV13: Drive [10]: Status indicator"
    fillColor:
      dataRef: "SV10TEPHV13: Drive [10]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-245:
    dataRef: "SV10TEPHV13: Drive [11]: Status indicator"
    fillColor:
      dataRef: "SV10TEPHV13: Drive [11]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-246:
    dataRef: "SV10TEPHV13: Drive [12]: Status indicator"
    fillColor:
      dataRef: "SV10TEPHV13: Drive [12]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-247:
    dataRef: "SV10TEPHV13: Drive [13]: Status indicator"
    fillColor:
      dataRef: "SV10TEPHV13: Drive [13]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-248:
    dataRef: "SV10TEPHV13: Drive [14]: Status indicator"
    fillColor:
      dataRef: "SV10TEPHV13: Drive [14]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-249:
    dataRef: "SV10TEPHV13: Drive [15]: Status indicator
    fillColor:
      dataRef: "SV10TEPHV13: Drive [15]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
  My1_Hk7sBKh1Tc-6wi9T-252:
    dataRef: "SV10TEPHV13: Drive [16]: Status indicator"
    fillColor:
      dataRef: "SV10TEPHV13: Drive [16]: Status indicator"
      datapoint: "last"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "red", level: 1}
        - {color: "orange", level: 2}
        - {color: "orange", level: 3}
        - {color: "orange", level: 4}
        - {color: "orange", level: 5}       
        - {color: "orange", level: 6}
        - {color: "orange", level: 10}
    linkRef: "grafana-home"
